"""add wallet profile image and display name

Revision ID: 300c983f967f
Revises: 7a2f8d7f51de
Create Date: 2026-03-01 20:15:44.277341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300c983f967f'
down_revision: Union[str, Sequence[str], None] = '7a2f8d7f51de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('profile_image_url', sa.Text(), nullable=True))
    op.add_column('wallets', sa.Column('display_name', sa.String(length=100), nullable=True))
    op.add_column('wallets', sa.Column('profile_fetched_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'profile_fetched_at')
    op.drop_column('wallets', 'display_name')
    op.drop_column('wallets', 'profile_image_url')
    # ### end Alembic commands ###
