"""add easy_win_ratio to trader_profiles

Revision ID: 70c8c3e23ec9
Revises: 300c983f967f
Create Date: 2026-03-01 21:21:43.374044

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70c8c3e23ec9"
down_revision: str | Sequence[str] | None = "300c983f967f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trader_profiles",
        sa.Column("easy_win_ratio", sa.Float(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trader_profiles", "easy_win_ratio")
    # ### end Alembic commands ###
